### ISSUE TITLE
OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by Billy1900** [AI-secure/DP-GCN#1]
System Version: Windows 10

When I ran your code, the error occurred as following,
<pre>
subdir = mode-raw_ratio-0.5_04-28-11:53:51.780
Traceback (most recent call last):
  File "D:\JetBrains\Toolbox\apps\PyCharm-P\ch-0\201.6668.115\plugins\python\helpers\pydev\pydevd.py", line 1438, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\JetBrains\Toolbox\apps\PyCharm-P\ch-0\201.6668.115\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:/1-Research/0-DP+GCN/Code/(2020-04-24)DP-GCN/main.py", line 126, in <module>
    main()
  File "E:/1-Research/0-DP+GCN/Code/(2020-04-24)DP-GCN/main.py", line 114, in main
    init_logger('./logs_{}'.format(args.dataset), subdir, print_log=False)
  File "E:\1-Research\0-DP+GCN\Code\(2020-04-24)DP-GCN\utils\logging.py", line 9, in init_logger
    fileHandler = logging.FileHandler("{0}/{1}.log".format(log_path, log_file))
  File "D:\Anaconda\envs\torch\lib\logging\__init__.py", line 1087, in __init__
    StreamHandler.__init__(self, self._open())
  File "D:\Anaconda\envs\torch\lib\logging\__init__.py", line 1116, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
OSError: [Errno 22] Invalid argument: 'E:\\1-Research\\0-DP+GCN\\Code\\(2020-04-24)DP-GCN\\logs_cora\\mode-raw_ratio-0.5_04-28-11:53:51.780.log'
</pre>

I still have not figured out how to make it.

**Comment by ghost** [comment]
https://python-forum.io/Thread-SOLVED-OSError-Errno-22-Invalid-argument?page=2
According to this post, the colon is not allowed in the filename in Windows. You can fix this error by changing the timing format in main.py line 88 from "%m-%d-%H:%M:%S.%f" to "%m-%d-%H-%M-%S.%f". I'll make an update in later versions. Thanks!
